### ISSUE TITLE
Mark the repository as deprecated (use the archive github feature)

### ISSUE THREAD

**Issue by evandrocoan** [arduino/actions#23]
I was using this action, but it does not support the `repo-token`, which is required.
1. https://github.com/actions/virtual-environments/issues/602#issuecomment-603035769 - API rate limit exceeded for Mac OS hosted by GitHub itself
1. https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories

**Comment by per1234** [comment]
This is a collection of actions. Some of the actions in this repository have been deprecated because they were moved to their own dedicated repositories so they could be published in the GitHub Marketplace. Other actions in this repository are still very much in use and under active development. So it wouldn't make sense for us to archive the repository or mark the entire repository deprecated (though it probably would have been best to put each action in its own repository from the start).

I see you were using the `arduino/actions/setup-protoc` action. As explained in https://github.com/actions/virtual-environments/issues/602#issuecomment-603035769, this is one of the deprecated actions. We have clearly stated that in the [action's readme](https://github.com/arduino/actions/tree/master/setup-protoc), and the link to the action on the repository's home page points to the new repository. So I don't think there is anything more we can do to resolve this situation here in this repository.

I see you already submitted an issue about the outdated readme in the other repository (https://github.com/arduino/setup-protoc/issues/4), and that surely should be resolved.

So I think this issue can be closed.

**Comment by evandrocoan** [comment]
Thanks for looking into it!
