### ISSUE TITLE
Error when using Taskfile installation action

### ISSUE THREAD

**Issue by huy-nguyen** [arduino/actions#55]
I'm trying to use your Taskfile action in [one of my repos](https://github.com/huy-nguyen/cloud-shell).
The Taskfile installation action succeeds but but I got [this error](https://github.com/huy-nguyen/cloud-shell/runs/687763610) when trying to invoke a task defined in [`Taskfile.yml`](https://github.com/huy-nguyen/cloud-shell/blob/master/Taskfile.yml):
```
##[debug]Evaluating condition for step: 'Build'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build
##[debug]Loading inputs
##[debug]Loading env
Run task build
##[debug]/bin/bash -e /home/runner/work/_temp/64677591-7311-4720-bc1f-1d8822b873af.sh
task: No Taskfile found on "Taskfile.yml". Use "task --init" to create a new one
##[error]Process completed with exit code 1.
##[debug]Finishing: Build
```
Am I missing something obvious here? Thanks!

**Comment by per1234** [comment]
Hi @huy-nguyen. You need to add [a checkout step](https://github.com/actions/checkout) to your workflow in order to make the contents of your repository available to the workflow (so Taskfile.yml will be present) before running `task`:
```yaml
      - name: Checkout repository
        uses: actions/checkout@v2
```

I just forked your repo and gave it a try and it looks like everything is working as expected. The `Build` step passes for me. The `Push` step does not, but not due to a missing Taskfile.yml.

So I'll go ahead and close this, but if you find there is an issue with the `arduino/actions/setup-taskfile`, please comment here and I'll reopen the issue.

**Comment by huy-nguyen** [comment]
@per1234 Thanks a lot for the help!
